### ISSUE TITLE
Why version 3?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [scopsy/await-to-js#49]
I see that a new major version was created, but I don't see any reason why this was done, according to this commit history.

**Comment by anton-white** [comment]
Same curiosity here!

**Comment by guirip** [comment]
The only difference between v2.1.1 and v3.0.0 seems to be this commit : https://github.com/scopsy/await-to-js/commit/8100f42ed4d06bddace603667c6fda91139a650e

I suppose the author bumped to a major version because despite the modification being very small it touches the API / main function signature.

A changelog would be greatly appreciated :)

**Comment by ahmadawais** [comment]
@scopsy A changelog or release notes would be super nice. Please consider.

**Comment by scopsy** [comment]
@guirip That's the changes that went into v3.
 Because the entire "library" is 4 lines long didn't want to break someone's code.

I'll try to create a changelog soon.
